# Generated by Django 3.2.18 on 2023-06-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='aspassword',
            new_name='adpassword',
        ),
    ]
