# Generated by Django 3.2.18 on 2023-06-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_rename_aspassword_admin_adpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adpassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
