# Generated by Django 3.2.18 on 2023-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.CharField(choices=[['CS', 'cash'], ['CR', 'credit card']], max_length=255),
        ),
    ]
