# Generated by Django 3.2.18 on 2023-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_order_total_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[['CS', 'cash'], ['CR', 'credit card']], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.CharField(max_length=255),
        ),
    ]
